name: "Model building composite run steps"
description: "Write model files using canned series of steps"
inputs:
  likelihood:
    description: "Probability distribution"
    required: true
  link:
    description: "Deterministic function for the mean"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo likelihood is ${{ inputs.likelihood }}
      shell: bash
    - run: echo link is ${{ inputs.link }}
      shell: bash
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    - run: |
        cd model-api
        git checkout gh-submodule
        cat README.md
        cd ..
      shell: bash
    - run: |
        cd model-api
        ./src/model-builder/compile-jags-file.sh \
          ${{ inputs.likelihood }} ${{ inputs.link }} b0-b1 w1 \
          ~/assets/${{ inputs.likelihood }}-${{ inputs.link }}
        ls ~/assets/${{ inputs.likelihood }}-${{ inputs.link }}
        cat ~/assets/${{ inputs.likelihood }}-${{ inputs.link }}/model.jags
      shell: bash
