name: "Model building composite run steps"
description: "Write model files using canned series of steps"
runs:
  using: "composite"
  steps:
    - run: echo 123
      shell: bash
    - run: echo 999
      shell: bash
