name: "Model building composite run steps"
description: "Write model files using canned series of steps"
inputs:
  data-type:
    description: "Data type"
    required: true
  likelihood:
    description: "Probability distribution"
    required: true
  link:
    description: "Deterministic function for the mean"
    required: true
  gle:
    description: "Group-level effect(s)"
    required: true
    default: b0
  demo:
    description: "Flag model as public-facing demo"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - run: echo likelihood is ${{ inputs.likelihood }}
      shell: bash
    - run: echo link is ${{ inputs.link }}
      shell: bash
    - run: |
        cd model-api
        git checkout gh-submodule
        cat README.md
        ls -a
        cd ..
      shell: bash
    - run: |
        cd model-api
        ./src/model-builder/compile-jags-file.sh \
          ${{ inputs.likelihood }} ${{ inputs.link }} ${{ inputs.gle }} w1 \
          $MODEL_PATH
      id: compile
      env:
        MODEL_PATH: ${{ github.workspace }}/assets/${{ inputs.data-type }}/${{ inputs.likelihood }}-${{ inputs.link }}-${{ inputs.gle }}
      shell: bash
    - run: |
        demo=${{ inputs.demo }}
        echo ${{ steps.compile.env.MODEL_PATH }}
        if [ $demo ]; then mkdir -p model-api/data-demo && cp -r ${{ steps.compile.env.MODEL_PATH }} model-api/data-demo; fi
        ls model-api/data-demo
        #if [ -z ${demo+x} ]; then echo "variable demo is unset"; else echo "demo is set to '$demo'"; fi
      shell: bash
