baseURL = "https://lzachmann.github.io/models-for-missing-data/"
languageCode = "en-us"
title = "Models for missing data"
theme = "book"

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'
