# Action metadata

name: "Call R"

description: "Run R script or command and record the time"

inputs:
  image:
    description: 'The container for the action'
    required: true
    default: 'Dockerfile'
  rfile: # R file name (including project path)
    description: 'Which R file'
    required: true
    default: 'model-api/.empty.R'
  args: # some applications may have positional parameters
    description: 'Arguments to the R script'
    required: false
  opts:
    description: 'Flags used by the R script'
    required: false


outputs:
  time: # id of output
    description: 'The time the task completed'

runs:
  using: "docker"
  image: ${{ inputs.image }} # was: ghcr.io/lzachmann/models-for-missing-data:main # was: "Dockerfile"
  args:
    - ${{ inputs.rfile }}
    - ${{ inputs.args }}
    - ${{ inputs.opts }}
