# Action metadata

name: "Call R"

description: "Run R script or command and record the time"

inputs:
  rfile: # R file name (including project path)
    description: 'Which R file'
    required: true
    default: 'model-api/.empty.R'
  args: # some applications may have positional parameters
    description: 'Arguments to the R script'
    required: false
  opts:
    description: 'Flags used by the R script'
    required: false

outputs:
  code: # id of output
    description: 'Process exit code'

runs:
  using: "docker"
  image: ghcr.io/lzachmann/models-for-missing-data:call-r # was: "Dockerfile"
  args:
    - ${{ inputs.rfile }}
    - ${{ inputs.args }}
    - ${{ inputs.opts }}

# TODO: https://stackoverflow.com/questions/58476228/how-to-use-a-variable-docker-image-in-github-actions
