# GitHub Pages workflow code

name: GitHub Pages # ==========================================================

on:
  push:
    branches: [ main ]
    paths:
      - "docs/website"
      - "!README.md" # don't rebuild on documentation changes
  pull_request:

jobs: # =======================================================================

  # ---------------------------------------------------------------------------
  deploy: # deploy the Hugo website we are using for documentation
  # ---------------------------------------------------------------------------
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true

      - name: Build
        run: |
          cd docs/website
          hugo --minify
          cd ../..

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/website/public
          publish_branch: gh-pages
