# Model workflow code

name: Model CI # ==============================================================

on: # controls when the workflow will run

  push: # trigger workflow on push events, but only for the main branch
    branches: [ main ]
    paths:
      - "model-api/**"
      - ".github/actions/build-model/**"
      - ".github/workflows/model.yml"
      - "!README.md" # don't rebuild on documentation changes

  pull_request: # triggers workflow on pull request events (main branch only)
    branches: [ main ] # ensure changes are "mergeable"

  workflow_dispatch: # permits manual triggers from the Actions tab

jobs: # =======================================================================

  # ---------------------------------------------------------------------------
  count-variables: # create all template models
  # ---------------------------------------------------------------------------

    strategy:
      matrix:
        likelihood: [poisson, negative-binomial, gen-pois]
        link: [linear, exponential]
        # exclude:
        #   # excludes parameterizations
        #   - likelihood: gen-pois
        #     link: linear
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Try a composite action (testing)
      - uses: ./.github/actions/build-model
        with:
          likelihood: ${{ matrix.likelihood }}
          link: ${{ matrix.link }}

      # Each artifact behaves as a file share. Uploading to the same artifact
      # multiple times in the same workflow can overwrite and append already
      # uploaded files.
      - name: Upload assets directory as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ github.sha }} # ${{ steps.findandreplace.outputs.value }}-artifact
          path: assets # ${{ github.workspace }}

  # ---------------------------------------------------------------------------
  create-jags-model-file-list:
  # ---------------------------------------------------------------------------

    needs: [count-variables]
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      # Download artifacts
      - name: Download file share
        uses: actions/download-artifact@v2
        with:
          name: artifact-${{ github.sha }}
          path: assets
      - name: Display structure of downloaded files
        run: ls -R
      - run: ls ~/assets/**/model.jags | awk ' BEGIN { ORS = ""; print "["; } { print "\/\@"$0"\/\@"; } END { print "]"; }' | sed "s^\"^\\\\\"^g;s^\/\@\/\@^\", \"^g;s^\/\@^\"^g"

    #   # here we create the json, we need the "id:" so we can use it in "outputs" bellow
    #   -
    #     id: set-matrix
    #     run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json --names)"
    #
    # # here, we save the result of this 1st phase to the "outputs"
    # outputs:
    #     matrix: ${{ steps.set-matrix.outputs.matrix }}

# ls | awk ' BEGIN { ORS = ""; print "["; } { print "\/\@"$0"\/\@"; } END { print "]"; }' | sed "s^\"^\\\\\"^g;s^\/\@\/\@^\", \"^g;s^\/\@^\"^g"

  # # ---------------------------------------------------------------------------
  # binomial-variables: # create all template models
  # # ---------------------------------------------------------------------------
  #
  #   strategy:
  #     matrix:
  #       likelihood: [binomial, beta-binomial]
  #       link: [inverse-logit]
  #       # exclude:
  #       #   # excludes parameterizations
  #       #   - likelihood: gen-pois
  #       #     link: linear
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true  # Fetch module and data API submodules
  #         fetch-depth: 0
  #
  #     # Try a composite action (testing)
  #     - uses: ./.github/actions/build-model
  #       with:
  #         likelihood: ${{ matrix.likelihood }}
  #         link: ${{ matrix.link }}

  # # ---------------------------------------------------------------------------
  # breadcrumbs: # artifacts
  # # ---------------------------------------------------------------------------
  #   steps:
  #     # Upload results
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: ${{ matrix.likelihood }}-models # was: ${{ steps.findandreplace.outputs.value }}-artifact
  #         path: ~/assets/${{ matrix.likelihood }}/**/*
  #         retention-days: 1
